remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Walter Brobson
description: I am a high school student who loves music and programming!
show_downloads: false
